name: RSpec

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  rspec:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.5.7]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run RSpec
      run: bundle exec rspec
